server:
  port: 8001

antrpc:
  port: 6060
  zk-servers: localhost:2181
  start-server: true
  interface-circuit-breaker:
    antrpc.test.api.UserServiceApi:
      threshold: 100
      check-interval-seconds: 10
    antrpc.boot.RpcApplicationListener:
      threshold: 10
      check-interval-seconds: 5
  circuit-breakers:
    threshold: 10
    check-interval-seconds: 10
  direct-hosts:
    antrpc.test.api.UserServiceApi: localhost:6060
  metrics-config:
    enable: false
    report-interval-seconds: 1
    enable-servlets: true
    enable-antrpc-monitor-reporter: true
  serialize-config:
    type: io.github.wanggit.antrpc.commons.codec.serialize.kryo.KryoSerializer
    map:
      max_idle: 20
      max_total: 100

spring:
  application:
    name: antrpctest
logging:
  level:
    antrpc.commons.codec.RpcProtocolEncoder: ERROR
    antrpc.client.zk.zknode.NodeHostContainer: ERROR
    antrpc.client.spring.CglibMethodInterceptor: ERROR
